apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-api
  namespace: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-api
  template:
    metadata:
      labels:
        app: ingestion-api
    spec:
      containers:
        - name: api
          image: ghcr.io/rawhideron/ragpipeline-api:f4f4eae480947c05947d7c7009d0d48c379f5e3c
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: rag-config
            - secretRef:
                name: rag-llm-secrets
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 8
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-api
  namespace: rag
spec:
  selector:
    app: ingestion-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  namespace: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
        - name: api
          image: ghcr.io/rawhideron/ragpipeline-api:f4f4eae480947c05947d7c7009d0d48c379f5e3c
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: rag-config
            - secretRef:
                name: rag-llm-secrets
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 8
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: rag
spec:
  selector:
    app: rag-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
